"""empty message

Revision ID: 089a948c7cf3
Revises: 
Create Date: 2020-02-25 20:50:48.577408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089a948c7cf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinksToFlavor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink', sa.String(length=50), nullable=True),
    sa.Column('drinkId', sa.Integer(), nullable=True),
    sa.Column('flavor', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinksToFlavor_drink'), 'drinksToFlavor', ['drink'], unique=False)
    op.create_index(op.f('ix_drinksToFlavor_drinkId'), 'drinksToFlavor', ['drinkId'], unique=False)
    op.create_index(op.f('ix_drinksToFlavor_flavor'), 'drinksToFlavor', ['flavor'], unique=False)
    op.create_table('flavor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flavor_name'), 'flavor', ['name'], unique=False)
    op.create_table('menuItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menuItem_description'), 'menuItem', ['description'], unique=False)
    op.create_index(op.f('ix_menuItem_name'), 'menuItem', ['name'], unique=True)
    op.create_index(op.f('ix_menuItem_popular'), 'menuItem', ['popular'], unique=False)
    op.create_index(op.f('ix_menuItem_price'), 'menuItem', ['price'], unique=False)
    op.create_table('roomnum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roomnum_num'), 'roomnum', ['num'], unique=False)
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_temp'), 'temp', ['temp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isActivated', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_isActivated'), 'user', ['isActivated'], unique=False)
    op.create_index(op.f('ix_user_user_type'), 'user', ['user_type'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('roomnum_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['roomnum_id'], ['roomnum.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_complete'), 'order', ['complete'], unique=False)
    op.create_index(op.f('ix_order_timestamp'), 'order', ['timestamp'], unique=False)
    op.create_table('drink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menuItem', sa.String(length=50), nullable=True),
    sa.Column('temp_id', sa.Integer(), nullable=False),
    sa.Column('decaf', sa.Boolean(), nullable=True),
    sa.Column('flavors', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('inst', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['temp_id'], ['temp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drink_decaf'), 'drink', ['decaf'], unique=False)
    op.create_index(op.f('ix_drink_flavors'), 'drink', ['flavors'], unique=False)
    op.create_index(op.f('ix_drink_inst'), 'drink', ['inst'], unique=False)
    op.create_index(op.f('ix_drink_menuItem'), 'drink', ['menuItem'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drink_menuItem'), table_name='drink')
    op.drop_index(op.f('ix_drink_inst'), table_name='drink')
    op.drop_index(op.f('ix_drink_flavors'), table_name='drink')
    op.drop_index(op.f('ix_drink_decaf'), table_name='drink')
    op.drop_table('drink')
    op.drop_index(op.f('ix_order_timestamp'), table_name='order')
    op.drop_index(op.f('ix_order_complete'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_type'), table_name='user')
    op.drop_index(op.f('ix_user_isActivated'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_temp_temp'), table_name='temp')
    op.drop_table('temp')
    op.drop_index(op.f('ix_roomnum_num'), table_name='roomnum')
    op.drop_table('roomnum')
    op.drop_index(op.f('ix_menuItem_price'), table_name='menuItem')
    op.drop_index(op.f('ix_menuItem_popular'), table_name='menuItem')
    op.drop_index(op.f('ix_menuItem_name'), table_name='menuItem')
    op.drop_index(op.f('ix_menuItem_description'), table_name='menuItem')
    op.drop_table('menuItem')
    op.drop_index(op.f('ix_flavor_name'), table_name='flavor')
    op.drop_table('flavor')
    op.drop_index(op.f('ix_drinksToFlavor_flavor'), table_name='drinksToFlavor')
    op.drop_index(op.f('ix_drinksToFlavor_drinkId'), table_name='drinksToFlavor')
    op.drop_index(op.f('ix_drinksToFlavor_drink'), table_name='drinksToFlavor')
    op.drop_table('drinksToFlavor')
    # ### end Alembic commands ###
