"""empty message

Revision ID: d164c6289484
Revises: cf04df649ca5
Create Date: 2023-05-11 17:22:15.524589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd164c6289484'
down_revision = 'cf04df649ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caf', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caf_caf'), 'caf', ['caf'], unique=False)
    op.create_table('drinksToCaffeine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink', sa.String(length=50), nullable=True),
    sa.Column('drinkId', sa.Integer(), nullable=True),
    sa.Column('caf', sa.String(length=50), nullable=True),
    sa.Column('cafId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafId'], ['caf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinksToCaffeine_caf'), 'drinksToCaffeine', ['caf'], unique=False)
    op.create_index(op.f('ix_drinksToCaffeine_cafId'), 'drinksToCaffeine', ['cafId'], unique=False)
    op.create_index(op.f('ix_drinksToCaffeine_drink'), 'drinksToCaffeine', ['drink'], unique=False)
    op.create_index(op.f('ix_drinksToCaffeine_drinkId'), 'drinksToCaffeine', ['drinkId'], unique=False)
    op.create_table('drinksToTemp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink', sa.String(length=50), nullable=True),
    sa.Column('drinkId', sa.Integer(), nullable=True),
    sa.Column('temp', sa.String(length=50), nullable=True),
    sa.Column('tempId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tempId'], ['temp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinksToTemp_drink'), 'drinksToTemp', ['drink'], unique=False)
    op.create_index(op.f('ix_drinksToTemp_drinkId'), 'drinksToTemp', ['drinkId'], unique=False)
    op.create_index(op.f('ix_drinksToTemp_temp'), 'drinksToTemp', ['temp'], unique=False)
    op.create_index(op.f('ix_drinksToTemp_tempId'), 'drinksToTemp', ['tempId'], unique=False)
    op.alter_column('HalfCaf', 'acc_order',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('drink', sa.Column('sf', sa.Boolean(), nullable=True))
    op.alter_column('drink', 'decaf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_drink_sf'), 'drink', ['sf'], unique=False)
    op.alter_column('favoriteDrinks', 'decaf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('menuItem', 'popular',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('order', 'complete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'isActivated',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'isActivated',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('order', 'complete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('menuItem', 'popular',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('favoriteDrinks', 'decaf',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_drink_sf'), table_name='drink')
    op.alter_column('drink', 'decaf',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('drink', 'sf')
    op.alter_column('HalfCaf', 'acc_order',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_drinksToTemp_tempId'), table_name='drinksToTemp')
    op.drop_index(op.f('ix_drinksToTemp_temp'), table_name='drinksToTemp')
    op.drop_index(op.f('ix_drinksToTemp_drinkId'), table_name='drinksToTemp')
    op.drop_index(op.f('ix_drinksToTemp_drink'), table_name='drinksToTemp')
    op.drop_table('drinksToTemp')
    op.drop_index(op.f('ix_drinksToCaffeine_drinkId'), table_name='drinksToCaffeine')
    op.drop_index(op.f('ix_drinksToCaffeine_drink'), table_name='drinksToCaffeine')
    op.drop_index(op.f('ix_drinksToCaffeine_cafId'), table_name='drinksToCaffeine')
    op.drop_index(op.f('ix_drinksToCaffeine_caf'), table_name='drinksToCaffeine')
    op.drop_table('drinksToCaffeine')
    op.drop_index(op.f('ix_caf_caf'), table_name='caf')
    op.drop_table('caf')
    # ### end Alembic commands ###
