"""empty message

Revision ID: d4c7148662c3
Revises: 021f9450f320
Create Date: 2022-03-03 20:28:00.680069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c7148662c3'
down_revision = '021f9450f320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HalfCaf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_order', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_HalfCaf_acc_order'), 'HalfCaf', ['acc_order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_HalfCaf_acc_order'), table_name='HalfCaf')
    op.drop_table('HalfCaf')
    # ### end Alembic commands ###
