"""empty message

Revision ID: e0fe92848a0d
Revises: 214010d4e25b
Create Date: 2020-03-03 20:53:53.864071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fe92848a0d'
down_revision = '214010d4e25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoriteDrinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('drinkId', sa.Integer(), nullable=True),
    sa.Column('menuId', sa.Integer(), nullable=True),
    sa.Column('tempId', sa.Integer(), nullable=True),
    sa.Column('decaf', sa.Boolean(), nullable=True),
    sa.Column('flavorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drinkId'], ['drink.id'], ),
    sa.ForeignKeyConstraint(['flavorId'], ['flavor.id'], ),
    sa.ForeignKeyConstraint(['menuId'], ['menuItem.id'], ),
    sa.ForeignKeyConstraint(['tempId'], ['temp.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favoriteDrinks_decaf'), 'favoriteDrinks', ['decaf'], unique=False)
    op.create_index(op.f('ix_favoriteDrinks_drinkId'), 'favoriteDrinks', ['drinkId'], unique=False)
    op.create_index(op.f('ix_favoriteDrinks_flavorId'), 'favoriteDrinks', ['flavorId'], unique=False)
    op.create_index(op.f('ix_favoriteDrinks_menuId'), 'favoriteDrinks', ['menuId'], unique=False)
    op.create_index(op.f('ix_favoriteDrinks_userId'), 'favoriteDrinks', ['userId'], unique=False)
    op.add_column('drinksToFlavor', sa.Column('flavorId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_drinksToFlavor_flavorId'), 'drinksToFlavor', ['flavorId'], unique=False)
    op.create_foreign_key(None, 'drinksToFlavor', 'flavor', ['flavorId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drinksToFlavor', type_='foreignkey')
    op.drop_index(op.f('ix_drinksToFlavor_flavorId'), table_name='drinksToFlavor')
    op.drop_column('drinksToFlavor', 'flavorId')
    op.drop_index(op.f('ix_favoriteDrinks_userId'), table_name='favoriteDrinks')
    op.drop_index(op.f('ix_favoriteDrinks_menuId'), table_name='favoriteDrinks')
    op.drop_index(op.f('ix_favoriteDrinks_flavorId'), table_name='favoriteDrinks')
    op.drop_index(op.f('ix_favoriteDrinks_drinkId'), table_name='favoriteDrinks')
    op.drop_index(op.f('ix_favoriteDrinks_decaf'), table_name='favoriteDrinks')
    op.drop_table('favoriteDrinks')
    # ### end Alembic commands ###
